var xxx = [["Hello","Please make your choice"]];
var one = [//advanced 1-25
  ["augury","предсказание","1"],
  ["prodigy","одаренный человек","2"],
  ["prolific","плодородный","3"],
  ["visionary","мечтательный","4"],
  ["deliberate","преднамеренный","5"],
  ["vigilance","бдительность","6"],
  ["stipulate","ставить условием","7"],
  ["blandishment","уговаривание","8"],
  ["moralistic","поучающий","9"],
  ["epistemology","теория познания","10"],
  ["incise","надрезать","11"],
  ["quintessential","наиболее типичный","12"],
  ["pervade","заполнять","13"],
  ["vitriolic","саркастический","14"],
  ["refulgent","сверкающий","15"],
  ["precursor","предшественник"],
  ["prevail","восторжествовать"],
  ["probity","честность"],
  ["encomium","восхваление"],
  ["feckless","беспомощный"],
  ["rarefy","разжижаться"],
  ["verisimilitude","правдоподобие"],
  ["untoward","неблагоприятный"],
  ["pillage","мародерство"],
  ["canonical","уставной"]
];
var two = [///advanced 25-50
  ["whittle","большой нож"],
  ["proprietary","патентованный"],
  ["dearth","дефицит"],
  ["dispatch","отправление"],
  ["glib","говорливый"],
  ["plumb","явный"],
  ["pejorative","бранный"],
  ["maudlin","плаксивый"],
  ["presumptuous","самонадеянный"],
  ["culpability","виновность"],
  ["disparage","принижать"],
  ["equivocation","уклонение"],
  ["penchant","склонность"],
  ["venerate","чтят"],
  ["throwback","движение назад"],
  ["vituperate","бранить"],
  ["abjure","отказываться"],
  ["dangle","болтаться"],
  ["diaphanous","прозрачный"],
  ["ossified","окостеневший"],
  ["parsimonious","экономный"],
  ["vindicate","отстаивать"],
  ["extirpate","вырывать с корнем"],
  ["doleful","скорбный"],
  ["precipitous","обрывистый"]
];
var introduction =  [
  ["we'll cover","мы рассмотрим"],
  ["concept ","понятие"],
  ["might ","можете"],
  ["we'll see tomorrow","завтра посмотрим"],
  ["sort of like","вроде как"],
  ["giant","гигант"],
  ["You mean like this one?","Вы имеете в виду, как этот?"],
  ["at different points in time","в различные моменты времени"],
  ["restore","восстановить"],
  ["compare","сравнить"],
  ["collaborate","сотрудничать"],
  ["contribute","делать вклад"],
  ["distribute","распространять"],
  ["back and forth","туда и обратно"],
  ["huge ","огромный"],
  ["efficient","эффективным"],
  ["to type","печатать"],
  ["a little bit like learning","немного похоже на обучение"],
  ["feel","чувствовать"],
  ["bit","немного"],
  ["not worth it","не стоит"],
  ["enough","достаточно"],
  ["internally","внутренне"],
  ["basically ","в основном"],
  ["It's kind of addicting.","Это своего рода увлечение."],
  ["out why ","почему"]
  ];
var courseOverview = [
  ["useful","полезный"],
  ["experience ","опыт"],
  ["matter ","дело"],
  ["particular ","конкретный"],
  ["sense","смысл"],
  ["rough","грубый"],
  ["breakdown","анализ, пробой"],
  ["stick","придерживаться"],
  ["through ","посредством"],
  ["explore","исследовать"],
  ["existing","существующий"],
  ["on your own","самостоятельно"],
  ["it might take awhile","Это может занять некоторое время"],
  ["it to explore ","Изучить"]
];
var differencesBetweenTwoFiles = [
  ["both","оба"],
   ["toolsthat","Инструмент"],
  ["intentional","Преднамеренный"],
  ["description","описание"],
  ["opportunity","возможность"],
  ["fill","заполнить"],
  ["could","мог"],
  ["ahead","вперед"],
  ["separate","отдельный"],
  ["commas","запятая"],
  ["decide","принимать решение"],
  ["typo","опечатка"],
  ["sounds","звуки"],
  ["fix","фиксировать, исправлять"],
  ["manually","вручную"],
  ["annoy","раздражать"],
  ["automatically","автоматически"],
  ["glad","радостный"],
  ["spend","проводить"],
  ["few","мало"],
  ["finding","обнаружение"],
  ["instead","вместо"]
];
var findingDiffsBetweenLargestFiles = [
    ["just found","только что нашел"],
    ["by hand","вручную"],
    ["probably","вероятно"],
    ["seem","казаться"],
    ["pretty","довольно, вполне"],
    ["tedious","утомительный"],
    ["require","требовать"],
    ["required","обязательный"],
    ["press space to start"," нажмите пробел, чтобы начать"],
    ["recognize you","узнаю тебя"],
    ["recognize me","Узнай меня"] ,
    ["that has been ported","которая была портированная"],
    ["the left and right arrow keys","клавиши со стрелками влево и вправо"] ,
    ["space to shoot","пробел чтобы стрелять"],
    ["up to fire the engine","вверх для зажигания двигатель"] ,
    ["props to Doug McGuiness","принадлежит DM"],
    ["complete the exercise","выполнить упражнение."] ,
    ["you won't(will not) have any problems","у вас не будет никаких проблем"],
    ["you won't need a burly system to run Civilization 6"," + "] ,
    ["intuitive","интуитивный"],
    ["burly","крепкий"]];

var findingDiffsBetweenLargestFiles2 = [
    ["thought","посредством,через"],
    ["move","шаг, двигаться"] ,
    ["entire","весь, целый"] ,
    ["the game out(out the game.)","выйти из игры"],
    ["engine","двигатель"] ,
    ["anymore","больше"],
    ["actions","действия"] ,
    ["consume","потреблять"],
    ["fortunately","к счастью"] ,
    ["bunch","группа, пучек"],
    ["which stands for file compare","который стоит(выступает) для сравнения файлов"] ,
    ["unrelate","несвязанный"],
    ["but you have a built-in tool","но у вас есть встроенный инструмент"] ,
    ["which stands for difference","которая выступает для сравнения"],
    ["I'll demonstrate","я продемонстрирую"] ,
    ["Then I'll ask you to go through","Тогда я буду просить вас, чтобы пройти через"],
    ["same","тот же"] ,
    ["By the way","кстати, между прочим"],
    ["if you'd prefer to use git bash","если вы предпочитаете использовать Git bash"] ,
    ["but for now","но сейчас"],
    ["pass","проходить"] ,
    ["hit","удар, поражать"],
    ["Then down here","Тогда здесь"] ,
    ["which was the description","которое были описаны"],
    ["Some description here changed ","Некоторые описание здесь изменения"] ,
    ["to the fun fact","на самом деле забавные"],
    ["sunflowers","подсолнухи"] ,
    ["pond","пруд"],
    ["disaster","катастрофа"] ,
    ["unify",""],
    ["Now, I'll go ahead and hit Enter","Теперь я иду дальше и нажимаю Enter"]];



var findingDiffsBetweenLargestFiles3 = [
    ["I'll scroll back up","+"],
    ["That is they existed in both the old version of the file and the new version","+"] ,
    ["Now I'll scroll back down","Теперь я буду прокручивать вниз"],
    ["And here's the style sheet change that you found earlier","+"] ,
    ["just like I did","так же, как я сделал"],
    ["Use the correct spelling for the word","Используйте правильное написание для слова"] ,
    ["Once you found the word, enter it in this box","После того, как вы нашли слово, введите его в этом поле"],
    ["entire","весь, целый"],
    ["which stand for file compare","Которые означают сравнение файлов"],
    ["It would be way too time consuming","Было бы слишком много времени"],
    ["manually","вручную"],
    ["unified","унифицированный"],
    ["ahead","вперед"],
    ["sign","знак, признак"],
    ["next to them","рядом с ними"],
    ["like these haven't changed","как они не изменились"],
    ["vice versa","наоборот"],
    ["earlier","ранее, раньше"],
    ["either","или, либо"],
    ["probably","вероятно"],
    ["similar","аналогичный, подобный"],
    ["same","тот же"],
    ["I'll change it back to space now","Я изменю его обратно в space прямо сейчас"],
    ["try out for","пробоваться"],
    ["try out","проверять"],
    ["far","далеко"],
    ["unrelated","Несвязанный"],
    ["to hand you over","передать вас"],
    ["reflect","отражать, отображать"],
    ["on what you","того, что вы"],
    ["compare","Сравнивать"],
    ["exist","существовать"],
    ["slightly","Немного"],
    ["So I'll have to look through for a little bit","Поэтому мне придется немного поразмыслить"],
    ["accomplish","выполнять, достигать совершенства"]
];

var reflections = [
    ["tutorial","учебник"],
    ["producing","Производящий"],
    ["Throughout ","На протяжении"],
    ["couple","пара, несколько"],
    ["helpful","полезный"],
    ["thought","думал, мысль"],
    ["mentioned","above"],
    ["assumes","предполагать"],
    ["logging",""],
    ["wait to see","Ждать, чтобы увидеть"],
    ["anyway","так или иначе"],
    ["mentioned","упомянутый"],
    ["available","доступный"],
    ["whatever","любой"],
    ["essential","существенный, основной"],
    ["unfamiliar","незнакомый"],
    ["advice","совет"],
    ["tempting","заманчивый"],
    ["cement","цемент"],
    ["seriously","серьезно"],
    ["research on this","исследования по этому вопросу"],
    ["later","позже"],
    ["practice","практика"],
    ["primary","первичный, основной"],
    ["prompt","подсказка"],
    ["set up","настроить"],
    ["reflection","отражение, размышление"],
    ["directions","направления"],
    ["separate","отдельный"],
    ["rich","богатые"],
    ["plain","простой, обычный"],
    ["take the time","не торопитесь"],
    ["reflect","задумайтесь, отражать"],
    ["easily","легко"],
    ["bug","ошибка"]];

var reflections2 =[
    ["access","доступ"],
    ["make sure","убеждаться, удостовериться"],
    ["as we mentioned previously","как мы уже упоминали ранее"],
    ["mention","упомянуть"],
    ["one that you like yet","тот, который вам нравится еще"],
    ["launch","запускать"],
    ["trouble","беспокойство, трудности"],
    ["setting up","настройка"],
    ["until","до"],
    ["able","в состоянии, способный"],
    ["hold","занимать, держать"],
    ["in either Git Bash or the terminal","+ either - или, либо"],
    ["rather than being","вместо того, чтобы"],
    ["rather than creating the file","не создавать файл"],
    ["response","ответ"],
    ["In the mean time","В это время"],
    ["though","хотя, однако"],
    ["a lot in this course","много в этом курсе"],
    ["refer","ссылаться, "],
    ["whatever","любой"],
    ["same","тот же"],
    ["pinpoint","определить, точный"],
    ["For this reason","По этой причине"],
    ["reasonably","разумно"],
    ["exact","точный"],
    ["matter","вопрос, дело"],
    ["preference","предпочтение"],
    ["break","сломить, разрыв"],
    ["thought","думал, мысль"]
];

var whereDoVersionCome = [
["against one another","Друг против друга"],
["conveniently","Удобно"],
["essay","сочинение"],
["and so on","и так далее"],
["likely","вероятно"],
["interact","Взаимодействовать"],
["periodically","периодически"],
["actually","на самом деле"],
["note that","Обратите внимание, что"],
["made by anyone","Сделано кем угодно"],
["revision","пересмотр, доработка"],
["through to see","Чтобы увидеть"],
["entire","весь"]];

var propertiesOfaVCS = [
["what would it look like","Как бы это выглядело"],
["specifically","В частности, конкретно"],
["In the rest of this lesson","В оставшейся части этого урока"],
["clearly","очевидно, конечно"],
["designed","предназначенный"],
["programmers tend to want in an editor",""],
["like syntax highlighting",""],
["parenthesis matching","?"],
["plausible","правдоподобный, вероятный"],
["As well","Также"],
["whatever","без разницы"],
["let you know","дам вам знать"],
["special purpose","спец. назначение"],
["similar","аналогичный"],
["I want to consider","Я хочу рассмотреть"],
["I'm going whether you like it or not","Я пойду, нравится тебе это или нет"],
["Consider a few different use case scenarios when you're coming up with your answer.","Рассмотрим несколько вариантов использования, когда вы придумываете свой ответ."],
["whenever","всякий раз, когда"]
]

var propertiesOfaVSCforCS =[
    ["Let's look through the option","Давайте рассмотрим вариант"],
    ["Your saved versions might not even compile, much less make sense as a logical checkpoint","Ваши сохраненные версии могут даже не компилироваться, а тем более иметь логическую контрольную точку."],
    ["advantage","преимущество"],
    ["if you tend to be forgetful","Если вы склонны забывать"],
    ["fine grain","мелкое зерно"],
    ["this one","вот этот"],
    ["otherwise","в противном случае"],
    ["much less","значительно меньше"],
    ["reason","Причина"],
    ["same","одна и та же"],
    ["that aren't actually usable","Которые фактически не пригодны"],
    ["unrelated","Несвязанный"],
    ["not so meaningful ones","Не столь значимые"],
    ["come up","подойти"],
    ["catch","поймать"],
    ["downside","Недостаток"],
    ["flexibility","Гибкость"]
    
]

var manualCommitInGit = [
["chart","диаграмма, график"],
["involve","включать(в себя)"],
["wonder","удивляться"],
["roughly","Примерно"],
["equivalent","эквивалент"],
["unpleasant","неприятный"],
["egotistical","самовлюбленный"],
["bastard","ублюдок, внебрачный"],
["built with that goal though","построенная с этой целью"],
["though","хотя, однако"],
["goal","цель"],
["widely-adopted","Широко принятый"],
["widely","широко"],
["adopted","Принятый, приемный"],
["also known as Subversion","Также известный как Subversion"],
["fairly","довольно"],
["extent","степень"],
["improved","улучшенный"],
["heard","услышанный"],
["mercury","ртуть"],
["abbreviated","сокращенный"],
["pretty","довольно"],
["lot","много"],
["leave","отпуск, оставлять"],
["leave the others off","Оставь других"],
["avoid","избежать"],
["cluttering","создавать суматоху, приводить в беспорядок"],
["chart","диаграмма"],
["cluttering up","Захламление"],
["So to avoid cluttering up our chart","Поэтому, чтобы не загромождать наш график"],
["entries","Записи"],
["versus","против"],
["clearly","очевидно"],
["require","требовать"],
["Wikipedia also requires this, so does SVN.","Википедия также требует этого, так же как и SVN."],
["save versions for you whether","Сохранить версии для вас, независимо от того,"],
["whether or not","так или иначе"],
["approach","подход"],
["allow","позволять"],
["Git takes the manual approach","Git использует ручной подход"],
["while","в то время как"],
["convenient","удобный"],
["represent","представлять"],
["expand","расширять"],
["able","в состоянии, способный"],
["if each checkpoint is meaningful","Если каждая контрольная точка имеет смысл"],
["supply","поставлять, снабжать"],
["pleasant","приятный"],
["assume","предполагать"],
["soon","в ближайшее время, скоро"],
["throughout","на протяжении"],
["let","позволять"]
]

var creatingInTheConceptMap= [
["relate","иметь отношение"],
["relate to one another","Связаны друг с другом"],
["fit","соответствовать, приспособленный"],
["grand","большой, грандиозный"],
["refer","обращаться, относиться"],
["allows","позволяет, "],
["whatever","без разницы"],
["recipe","рецепт"],
["node","узел"],
["annotate","аннотировать"],
["type of","тип"],
["But if we do that","Но если мы это сделаем"],
["clutter","беспорядок, суматоха"],
["tiny","крошечный"],
["indicate","указывать, означать"],
["relationship","связь, отношение"],
["gather","собирать, собираться"],
["mention","упомянуть"],
["from time to time","время от времени"],
["contrast","контрастировать, контраст"],
["comparison","сравнение"],
["chart","диаграмма"],
["recent","недавний, последний"],
["across","через"],
["come across","Натолкнуться"],
["directly","непосредственно"],
["related","Связанный, родственный"],
["out of hand","из рук"],
["get out of hand","выйти из-под контроля"],
["involve","включать, предполагать"],
["But they don't actually call them that","Но на самом деле они их не называют"],
["just keep it","Просто держи"],
["as the ones we already have","Как те, которые у нас уже есть"],
["Remember that those were type of connections.","Помните, что это были типы соединений."],
["rather","скорее"],
["We'll use green for that.","Для этого мы будем использовать зеленый цвет."],
["And we'll add the label here.",""],
["Note this time","Обратите внимание на этот раз"],
["later on","позже"]
]

var usingGitViewHistory = [
["i'm about to","я собираюсь"],
["to take a closer look at","Присмотреться"],
["specifically","конкретно"],
["I'll take a look at","Я посмотрю на"],
["closer","ближе"],
["What I get is","То, что я получаю"],
["Notice","Обратите внимание, уведомление"],
["explain","объяснять"],
["uniquely","однозначно"],
["movement","движение"],
["lets you refer to it","Позволяет вам ссылаться на него"],
["revert","возвращаться"],
["within","в, в пределах"],
["you'll notice","Вы заметите"],
["familiar","привычный, близкий"],
["Here's the typo you found.","Вот опечатка, которую вы нашли."],
["All right, so where should we add diff?","Хорошо, так где мы должны добавить diff?"],
["indirectly","косвенно"],
["we're going to call this the operates-on relationship","Мы будем называть это оперирующими отношениями"],
["span","охватывать, диапазон"],
["currently","В данный момент"],
["define","определять"],
["If you want to change this function to take an additional argument","Если вы хотите изменить эту функцию, чтобы принять дополнительный аргумент"],
["you'll need to simultaneously change code in both files","Вам нужно будет одновременно изменить код в обоих файлах"],
["simultaneously","одновременно"],
["mention","упомянуть"],
["files are tracked one at a time","Файлы отслеживаются по одному за раз"],
["one at a time","один за раз"],
["I made either of the edits","Я сделал одно из изменений"],
["first I have to find the right version in one doc","Сначала я должен найти нужную версию в одном документе"],
["approximately","приблизительно"],
["dig","копать"],
["the same time","в то же время"],
["doable","выполнимый"],
["about whether","О том"],
["tracking","отслеживание"],
["competition","соревнование"],
["solve","решать"],
["make up","составить"],
["split up","разделить"],
["rather than","скорее, чем"],
["rather than separately","А не отдельно"]
];
