var xxx = [["Hello","Please make your choice"]];
var one = [//advanced 1-25
  ["augury","предсказание","1"],
  ["prodigy","одаренный человек","2"],
  ["prolific","плодородный","3"],
  ["visionary","мечтательный","4"],
  ["deliberate","преднамеренный","5"],
  ["vigilance","бдительность","6"],
  ["stipulate","ставить условием","7"],
  ["blandishment","уговаривание","8"],
  ["moralistic","поучающий","9"],
  ["epistemology","теория познания","10"],
  ["incise","надрезать","11"],
  ["quintessential","наиболее типичный","12"],
  ["pervade","заполнять","13"],
  ["vitriolic","саркастический","14"],
  ["refulgent","сверкающий","15"],
  ["precursor","предшественник"],
  ["prevail","восторжествовать"],
  ["probity","честность"],
  ["encomium","восхваление"],
  ["feckless","беспомощный"],
  ["rarefy","разжижаться"],
  ["verisimilitude","правдоподобие"],
  ["untoward","неблагоприятный"],
  ["pillage","мародерство"],
  ["canonical","уставной"]
];
var two = [///advanced 25-50
  ["whittle","большой нож"],
  ["proprietary","патентованный"],
  ["dearth","дефицит"],
  ["dispatch","отправление"],
  ["glib","говорливый"],
  ["plumb","явный"],
  ["pejorative","бранный"],
  ["maudlin","плаксивый"],
  ["presumptuous","самонадеянный"],
  ["culpability","виновность"],
  ["disparage","принижать"],
  ["equivocation","уклонение"],
  ["penchant","склонность"],
  ["venerate","чтят"],
  ["throwback","движение назад"],
  ["vituperate","бранить"],
  ["abjure","отказываться"],
  ["dangle","болтаться"],
  ["diaphanous","прозрачный"],
  ["ossified","окостеневший"],
  ["parsimonious","экономный"],
  ["vindicate","отстаивать"],
  ["extirpate","вырывать с корнем"],
  ["doleful","скорбный"],
  ["precipitous","обрывистый"]
];
var three =  [
  ["andrey1","three"],
  ["andrey2","three"],
  ["andrey3","three"],
  ["andrey4","three"],
  ["andrey5","three"],
  ["andrey6","three"],
  ["andrey7","three"],
  ["andrey6","three"],
  ["andrey7","three"],
  ["andrey8","three"],
  ["andrey1","three"],
  ["andrey2","three"],
  ["andrey3","three"],
  ["andrey4","three"],
  ["andrey5","three"],
  ["andrey6","three"],
  ["andrey7","three"],
  ["andrey6","three"],
  ["andrey7","three"],
  ["andrey8","three"],
  ["andrey6","three"],
  ["andrey7","three"],
  ["andrey6","three"],
  ["andrey7","three"],
  ["andrey8","three"]
  ];
var four = [
  ["andrey1","three"],
  ["andrey2","three"],
  ["andrey3","three"],
  ["andrey4","three"],
  ["andrey5","three"],
  ["andrey6","three"],
  ["andrey7","three"],
  ["andrey6","three"],
  ["andrey7","three"],
  ["andrey8","three"],
  ["andrey1","three"],
  ["andrey2","three"],
  ["andrey3","three"],
  ["andrey4","three"],
  ["andrey5","three"],
  ["andrey6","three"],
  ["andrey7","three"],
  ["andrey6","three"],
  ["andrey7","three"],
  ["andrey8","three"],
  ["andrey6","three"],
  ["andrey7","three"],
  ["andrey6","three"],
  ["andrey7","three"],
  ["andrey8","three"]
];
var dafault = [
  ["andrey1","dafault"],
  ["andrey2","dafault"],
  ["andrey3","dafault"],
  ["andrey4","dafault"],
  ["andrey5","dafault"],
  ["andrey6","dafault"],
  ["andrey7","dafault"],
  ["andrey8","dafault"],
  ["andrey9","dafault"]
];
